# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [3]:
import numpy as np



2. Create a null vector of size 10 

In [4]:
xnv = np.zeros(10)
xnv

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [6]:
vec10_49 = np.arange(10,49)
vec10_49

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

4. Find the shape of previous array in question 3

In [7]:
vec10_49.shape

(39,)

5. Print the type of the previous array in question 3

In [9]:
type(vec10_49[10])

numpy.int32

6. Print the numpy version and the configuration


In [11]:
conda list numpy

# packages in environment at C:\Users\STA\anaconda3:
#
# Name                    Version                   Build  Channel
numpy                     1.18.1           py37h93ca92e_0  
numpy-base                1.18.1           py37hc3f5095_1  
numpydoc                  0.9.2                      py_0  

Note: you may need to restart the kernel to use updated packages.


In [13]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/STA/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/STA/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/STA/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Us

7. Print the dimension of the array in question 3


In [17]:
vec10_49.ndim

1

8. Create a boolean array with all the True values

In [15]:
np.ones((9), dtype=bool)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

9. Create a two dimensional array




In [19]:
td = np.zeros((3,4))
td

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

10. Create a three dimensional array



In [20]:
thrd = np.zeros((2,3,4))
thrd

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [22]:
rev = vec[::-1]
rev

array([49, 10])

12. Create a null vector of size 10 but the fifth value which is 1 

In [24]:
nvec = np.zeros(10)
nvec[5] = 1
nvec

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [25]:
matrix1=np.identity(3)
matrix1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [26]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [27]:
arr.dtype

dtype('int32')

In [28]:
#Changing the data type of numpy array using astype() method from int to float
arr=arr.astype(np.float64)
arr

array([1., 2., 3., 4., 5.])

In [29]:
arr.dtype

dtype('float64')

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [30]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [31]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 

arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
np.in1d(arr1, arr2)

array([ True,  True, False,  True, False, False])

17. Extract all odd numbers from arr with values(0-9)

In [32]:
odn=np.arange(0,10)
odn[1:10:2]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [81]:
x = np.arange(0,10)
print(x)
y=x[1:10:2]
print(y)
(np.where(x=[y], -1, x))



SyntaxError: positional argument follows keyword argument (<ipython-input-81-c3f383ebc539>, line 5)

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [96]:
arr = np.arange(10)
print(arr)
arr8=arr[5: -1 9]= 12
print(arr8)

[0 1 2 3 4 5 6 7 8 9]


IndexError: too many indices for array

20. Create a 2d array with 1 on the border and 0 inside

In [106]:
x = np.ones((5,5))
print(x)
x[1:-1,1:-1] = 0
print(x)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [114]:
arr2d = np.array([1, 2, 3,[4, 5, 6],[7, 8, 9]])
print(arr2d)
y=arr2d[arr2d==5] = 12
print(y)

[1 2 3 list([4, 5, 6]) list([7, 8, 9])]
12


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

26. Create a 10x10 array with random values and find the minimum and maximum values

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

33. Swap axes of the array you created in Question 32

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


40. Generate a matrix of 20 random values and find its cumulative sum

In [103]:
x = np.arange(10)
x[::-1].cumsum()[::-1]

array([45, 45, 44, 42, 39, 35, 30, 24, 17,  9], dtype=int32)